config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "welcome#index"
  get "/login_form", to: "users#login_form", as: "login_form"
  get "/login", to: "users#login", as: "login"
  get "/logout", to: "users#logout", as: "logout"
  get "/auth/github/callback", to: "users#github_callback"

  resources :users, only: [:new, :create] do
    get "/dashboard", to: "users#dashboard"
  end

  resources :lessons, only: [:index, :show]
  # resources :ruby_lessons, only: [:index, :show]
  # resources :javascript_lessons, only: [:index, :show]
  # resources :interview_lessons, only: [:index, :show]
  post "/openai" => "openai#tell_me_more", as: :openai
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @_current_user = session[:user_id]
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_user
  before_action :set_lesson_type

  def index
    @lessons = LessonsFacade.new(@lesson_type).all
  end

  def show
    @topic = "#{@lesson_type.capitalize} Lesson"
    @lesson = LessonsFacade.new.detail(params[:id])
    @formatted_lesson = markdown_to_html(@lesson.lesson)
    render "shared/lesson_show"
  end
  
  def get_ai_response
    @response = OpenAiFacade.new.get_response(params[:id])
  end

  private

  def set_user
    @user = UserFacade.new.get_user(session[:user_id]) if session[:user_id]
  end

  def set_lesson_type
    @lesson_type = params[:type]
  end

  def markdown_to_html(content)
    renderer = Redcarpet::Render::HTML.new
    markdown = Redcarpet::Markdown.new(renderer, {
      autolink: true,
      tables: true,
      fenced_code_blocks: true,
      strikethrough: true,
      superscript: true,
      underline: true,
      highlight: true,
      quote: true,
      footnotes: true,
      lax_spacing: true
    })
    markdown.render(content).html_safe
  end
end

app/controllers/openai_controller.rb
class OpenaiController < ApplicationController
  def tell_me_more
    markdown_response = OpenaiFacade.new.get_response(params)
    @response = markdown_to_html(markdown_response.response)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("tell-me-more-button", partial: "empty"),
          turbo_stream.replace("openai-response", partial: "openai_response", locals: { response: @response })
        ]
      end
    end
  end

  def markdown_to_html(content)
    renderer = Redcarpet::Render::HTML.new
    markdown = Redcarpet::Markdown.new(renderer, {
      autolink: true,
      tables: true,
      fenced_code_blocks: true,
      strikethrough: true,
      superscript: true,
      underline: true,
      highlight: true,
      quote: true,
      footnotes: true,
      lax_spacing: true
    })
    markdown.render(content).html_safe
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
    @user = UserFacade.new.get_user(params[:id])
  end

  def create
    response = UserFacade.new.create_user(user_params)
    if response[:id]
      session[:user_id] = response[:id]
      flash[:success] = "Welcome #{response[:attributes][:username]}"
      redirect_to root_path
    else
      flash[:error] = "Sorry, your credentials are bad: #{response[:errors]}"
      redirect_to new_user_path
    end
  end

  def login_form
  end

  def login
    response = UserFacade.new.login(user_params)
    if response[:id]
      session[:user_id] = response[:id]
      flash[:success] = "Welcome #{response[:attributes][:username]}"
      redirect_to root_path
    else
      flash[:error] = "Sorry, your credentials are bad #{response[:errors]}"
      redirect_to login_form_path
    end
  end

  def github_callback
    user = GithubFacade.github_user(params[:code])
    if user[:data] && user[:data][:id]
      session[:user_id] = user[:data][:id]
      flash[:success] = "Welcome #{user[:data][:attributes][:username]}!"
      redirect_to root_path
    else
      flash[:error] = "Sorry, your credentials are bad"
      redirect_to new_user_path
    end
  end

  def logout
    session.delete :user_id
    redirect_to root_path
    flash[:success] = "Logged out successfully"
  end

  private

  def user_params
    params.permit(:username, :password, :phone_num, :email, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = UserFacade.new.get_user(session[:user_id]) if session[:user_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConsultancyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper d-flex flex-column flex-grow-1">
      <%= render partial: "shared/nav" %>
      <% flash.each do |type, message| %>
        <section class=<%= type %>>
        <p><%= message %></p>
        </section>
      <% end %>
      <div class="flex-grow-1">
        <%= yield %>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/lessons/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-xl-8">
      <h2 class="mb-4"><%= params[:type].capitalize %> Lessons</h2>

      <div class="row">
        <% @lessons.each do |lesson| %>
          <div class="col-md-6 mb-4">
            <div class="card custom-shadow2">
              <div class="card-body d-flex">
                <div class="icon-container mr-3 ">
                  <% if params[:type] == "javascript" %>
                    <i class="fa-brands fa-js fa-3x" style="color: #ee6826;"></i>
                  <% elsif params[:type] == "ruby" %>
                    <i class="fa-regular fa-gem fa-rotate-by fa-2xl" style="color: #ee6826; --fa-rotate-angle: 320deg;"></i>
                  <% else %>
                    <i class="fa-solid fa-code fa-xl" style="color: #e66826;"></i>
                  <% end %>
                </div>
                <div class="ms-3">
                  <h5 class="card-title">
                    <%= link_to lesson_path(type: @lesson_type, id: lesson.id), class: "link-hide stretched-link" do %>
                      Lesson: <%= lesson.topic %>
                    <% end %>
                  </h5>
                  <p class="card-text">
                    <% if params[:type] == "javascript" %>
                      <span> Learn <%= lesson.topic %> in JavaScript</span>
                    <% elsif params[:type] == "ruby" %>
                      <span> Learn <%= lesson.topic %> in Ruby</span>
                    <% else %>
                      <span> Practice <%= lesson.topic %> interview questions</span>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/openai/_openai_response.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-12 col-md-11 col-lg-10 col-xl-10">
    <%= @response %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="footer-text">Snackable Code Refreshments</p>
  </div>
  <div class="footer-row row-1"></div>
  <div class="footer-row row-2"></div>
  <div class="footer-row row-3"></div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-custom container-fluid nav-shadow">
  <div class="container">
    <a class="navbar-brand" href="/">
      <h3><i class="fa-solid fa-cookie-bite fa-bounce" style="color: #ff7300;"></i>CodeSnacks</h3>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Ruby", lessons_path(type: "ruby"), class: "nav-link active", aria: { current: "page" } %>
        </li>
        <li class="nav-item">
          <%= link_to "JavaScript", lessons_path(type: "javascript"), class: "nav-link active", aria: { current: "page" } %>
        </li>
        <li class="nav-item">
          <%= link_to "Interview Questions", lessons_path(type: "interview"), class: "nav-link active", aria: { current: "page" } %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <% if current_user %>
          Logged in as: <%= @user.username %>
          <%= link_to "Log out", logout_path, class: "btn custom-btn1 mr-2 custom-shadow2" %>
        <% else %>
          <%= link_to "Sign Up", new_user_path, class: "btn custom-btn1 mr-2 custom-shadow2" %>
          <%= link_to "Log In", login_form_path, class: "btn custom-btn2 custom-shadow2 ms-3" %>
        <% end %>
      </form>
    </div>
  </div>
</nav>

app/views/shared/lesson_show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-12 col-md-11 col-lg-10 col-xl-10">
      <div class="card custom-shadow2">
        <div class="card-body">
          <h2 class="card-title mb-4"><%= @topic %></h2>

          <div class="mb-4">
            <h5 class="text-muted">Topic</h5>
            <p class="lead"><%= @lesson.topic %></p>
          </div>

          <div class="mb-4">
            <h5 class="text-muted">Lesson Content</h5>
            <%= @formatted_lesson.html_safe %>
          </div>

          <div class="mb-4">
            <h5 class="text-muted">Additional Resources</h5>
            <%= link_to "Learn More", @lesson.link, target: '_blank', class: "btn custom-btn1 custom-shadow mt-2" %>
          </div>

          <% if session[:user_id].present? %>
            <div class="mt-5">
              <h5 class="text-muted mb-3">Need more information?</h5>
              <%= turbo_frame_tag "tell-me-more-button" do %>
                <%= button_to "Tell Me More", openai_path, params: {lesson: @lesson.topic, topic: @topic}, method: :post,
                  data: { turbo_frame: "openai-response" }, class: "btn custom-btn2 custom-shadow" %>
              <% end %>

              <div class="mt-4">
                <%= turbo_frame_tag "openai-response" do %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">

    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-xl-8 custom-shadow2">
      <h4 class="mt-5 text-center">Login</h4>
      <div class="row mt-4 p-3">
        <div class="col-md-6 mb-4 border p-3">
          <%= form_with url: login_path, method: :get do |f| %>
            <div class="mb-3">
              <%= f.label :email, "Email:", class: "form-label" %>
              <%= f.text_field :email, class: "form-control", required: true %>
            </div>
            <div class="mb-3">
              <%= f.label :password, "Password:", class: "form-label" %>
              <%= f.password_field :password, class: "form-control", required: true %>
            </div>
            <div class="d-grid">
              <%= f.submit "Log In", class: "btn custom-btn1 custom-shadow2", required: true %>
            </div>
          <% end %>
        </div>

        <div class="col-md-6 mb-4">
          <div class="d-flex flex-column justify-content-center h-100">
            <%= link_to "Login with GitHub ", "https://github.com/login/oauth/authorize?client_id=#{Rails.application.credentials.github[:client_id]}&scope=repo", data: { turbo: false }, class: "btn custom-btn1 btn-lg custom-shadow2" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="body">
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-xl-8 custom-shadow2 p-3">
        <h4 class="mt-5 text-center">Create a New User</h4>

        <div class="row mt-4">
          <div class="col-md-7 border p-3">
            <%= form_with url: users_path, method: :post do |f| %>
              <div class="mb-2">
                <%= f.label :username, "Username:", class: "form-label" %>
                <%= f.text_field :username, class: "form-control", required: true %>
              </div>
              <div class="mb-2">
                <%= f.label :email, "Email:", class: "form-label" %>
                <%= f.text_field :email, class: "form-control", required: true %>
              </div>
              <div class="mb-2">
                <%= f.label :phone_number, "Phone Number", class: "form-label" %>
                <%= f.text_field :phone_number, class: "form-control", pattern: "[0-9]{10}", placeholder: "1234567890" %>
              </div>
              <div class="mb-3">
                <%= f.check_box :text_preference, as: :boolean, checked_value: 'true', unchecked_value: 'false' %>
                <%= f.label :text_preferences, "Yes, you can text me reminders", class: "form-label" %>
              </div>
              <div class="mb-2">
                <%= f.label :password, "Password:", class: "form-label" %>
                <%= f.password_field :password, class: "form-control", required: true, minlength: 6 %>
              </div>
              <div class="mb-3">
                <%= f.label :password_confirmation, "Password Confirmation:", class: "form-label" %>
                <%= f.password_field :password_confirmation, class: "form-control", required: true, minlength: 6 %>
              </div>
              <div class="d-grid">
                <%= f.submit "Create User", class: "btn custom-btn1 custom-shadow" %>
              </div>
            <% end %>
          </div>

          <div class="col-md-5 mb-4">
            <div class="d-flex flex-column justify-content-center h-100">
              <%= link_to "Sign up with Github", "https://github.com/login/oauth/authorize?client_id=#{Rails.application.credentials.github[:client_id]}&scope=repo", data: { turbo: false }, class: "btn custom-btn1 btn-lg custom-shadow2" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row justify-content-center text-center">
    <div class="col-md-8">
      <h1 class="display-1 mt-5 mb-3">CodeSnacks</h1>
      <p class="lead mb-5">Bite-sized coding lessons to satisfy your learning appetite</p>
      <% if current_user %>
        <p class="lead mb-5">Thank you for signing up</p>
      <% else %>
        <div class="row justify-content-center">
          <div class="col-md-4 mb-3">
            <%= link_to "Sign Up", new_user_path, class: "btn custom-btn1 btn-lg btn-block custom-shadow" %>
          </div>
          <div class="col-md-4 mb-3">
            <%= link_to "Log In", login_form_path, class: "btn custom-btn2 btn-lg btn-block custom-shadow mb-1" %>
          </div>
          <p class="lead mb-5 ">sign up or login to gain access to ai powered insights</p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-md-4 text-center mb-4">
      <h3>Ruby</h3>
      <p>Master the elegant syntax of Ruby</p>
      <%= link_to "Start Learning Ruby", lessons_path(type: "ruby"), class: "btn custom-btn1 custom-shadow" %>
    </div>
    <div class="col-md-4 text-center mb-4">
      <h3>JavaScript</h3>
      <p>Dive into the world of interactive web development</p>
      <%= link_to "Explore JavaScript", lessons_path(type: "javascript"), class: "btn custom-btn1 custom-shadow" %>
    </div>
    <div class="col-md-4 text-center mb-4">
      <h3>Interview Questions</h3>
      <p>Prepare for your next coding interview</p>
      <%= link_to "Practice Questions", lessons_path(type: "interview"), class: "btn custom-btn1 custom-shadow" %>
    </div>
  </div>
</div>